[package]
name = "cleanup"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
demostf-client = "0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
main_error = "0.1"
dotenv = "0.15"